---
- name: Download g (simple golang version manager)
  get_url:
    url: https://git.io/g-install
    dest: /tmp/g-install
    mode: 0550

- name: Setup g version manager
  command: /tmp/g-install -y bash zsh

- name: Clean
  become: yes
  file:
    state: absent
    path: /tmp/g-install

- name: Enable Go modules
  lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^GO111MODULE="
    line: "GO111MODULE=on"

- name: Install go
  command: "g install {{ golang_version }}"

- name: Setup go
  command: "g set {{ golang_version }}"

- name: Go packages install
  command: "go get {{ item.name }}@{{ item.version }}"
  loop: "{{ golang_packages }}"
