---

- name: Download n (simple node version manager)
  get_url:
    url: https://raw.githubusercontent.com/tj/n/master/bin/n
    dest: /usr/local/bin/n
    mode: 0550

- name: Setup n
  command: "n {{ node_version }}"

- name: "Yarn | Check for installation"
  command: which yarn
  register: yarn_result
  changed_when: false
  failed_when: false

- name: "Yarn | Register existing installation status"
  set_fact:
    yarn_install_state: true
  changed_when: false
  when: '"yarn" in yarn_result.stdout or yarn_result.rc != 0'

- name: "Yarn | Register existing installation status (true)"
  set_fact:
    yarn_install_state: false
  changed_when: false
  when:
    - 'yarn_result.rc == 0'
    - '"Usage" not in yarn_result.stdout'
    - '"Yarn requires Node" not in yarn_result.stdout'
    - '"is not supported, please use Node.js" not in yarn_result.stdout'

- name: "Yarn | Include OS-specific tasks"
  include_tasks: "yarn-{{ ansible_os_family }}.yml"
  when: yarn_install_state

- name: "Yarn | Install"
  package:
    name: yarn
    state: present
  when: yarn_install_state
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
