---
- name: install python modules
  pip:
    name:  "{{ pip_packages }}"
    state: present
  become: yes
  become_user: root

- name: force reinstall python modules
  pip:
    name:  "{{ pip_packages_force }}"
    state: forcereinstall
  become: yes
  become_user: root
